"""baseline schema from SQLModel metadata

Revision ID: f77e214dfd32
Revises: 
Create Date: 2026-09-28 22:04:33.975287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emitted sqlmodel.sql.sqltypes.AutoString for every String column
# but did not add the import itself.
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f77e214dfd32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badgedef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_name'), 'board', ['name'], unique=True)
    op.create_table('passwordresetcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('used_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresetcode_email'), 'passwordresetcode', ['email'], unique=False)
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('medium', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('village', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_grade', sa.Integer(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_board'), 'subject', ['board'], unique=False)
    op.create_index(op.f('ix_subject_class_grade'), 'subject', ['class_grade'], unique=False)
    op.create_table('textbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_grade', sa.Integer(), nullable=False),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deep_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('last_checked', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_ok', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textbook_board'), 'textbook', ['board'], unique=False)
    op.create_index(op.f('ix_textbook_class_grade'), 'textbook', ['class_grade'], unique=False)
    op.create_index(op.f('ix_textbook_lang'), 'textbook', ['lang'], unique=False)
    op.create_index(op.f('ix_textbook_subject_name'), 'textbook', ['subject_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang_pref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_grade', sa.Integer(), nullable=True),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('parent_of_id', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_pic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_of_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_grade', sa.Integer(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('ratings_count', sa.Integer(), nullable=False),
    sa.Column('students_count', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('thumb_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_board'), 'course', ['board'], unique=False)
    op.create_index(op.f('ix_course_class_grade'), 'course', ['class_grade'], unique=False)
    op.create_index(op.f('ix_course_slug'), 'course', ['slug'], unique=True)
    op.create_index(op.f('ix_course_subject_id'), 'course', ['subject_id'], unique=False)
    op.create_table('dailyactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('quizzes_taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailyactivity_date'), 'dailyactivity', ['date'], unique=False)
    op.create_index(op.f('ix_dailyactivity_user_id'), 'dailyactivity', ['user_id'], unique=False)
    op.create_table('doubt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doubt_student_id'), 'doubt', ['student_id'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_grade', sa.Integer(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('uploader_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('source_of_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_board'), 'material', ['board'], unique=False)
    op.create_index(op.f('ix_material_class_grade'), 'material', ['class_grade'], unique=False)
    op.create_index(op.f('ix_material_subject_name'), 'material', ['subject_name'], unique=False)
    op.create_index(op.f('ix_material_uploader_id'), 'material', ['uploader_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('topicstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topicstats_subject_name'), 'topicstats', ['subject_name'], unique=False)
    op.create_index(op.f('ix_topicstats_topic'), 'topicstats', ['topic'], unique=False)
    op.create_index(op.f('ix_topicstats_user_id'), 'topicstats', ['user_id'], unique=False)
    op.create_table('userbadge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userbadge_badge_code'), 'userbadge', ['badge_code'], unique=False)
    op.create_index(op.f('ix_userbadge_user_id'), 'userbadge', ['user_id'], unique=False)
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('cert_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_id')
    )
    op.create_index(op.f('ix_certificate_user_id'), 'certificate', ['user_id'], unique=False)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_course_id'), 'chapter', ['course_id'], unique=False)
    op.create_table('doubtreply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doubt_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doubt_id'], ['doubt.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doubtreply_doubt_id'), 'doubtreply', ['doubt_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_course_id'), 'enrollment', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollment_user_id'), 'enrollment', ['user_id'], unique=False)
    op.create_table('materialreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materialreport_material_id'), 'materialreport', ['material_id'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_url_low', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('estimate_mb', sa.Float(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_chapter_id'), 'lesson', ['chapter_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_lesson_id'), 'note', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_note_user_id'), 'note', ['user_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_lesson_id'), 'progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_chapter_id'), 'question', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_question_lesson_id'), 'question', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_question_topic'), 'question', ['topic'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_mr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('time_limit_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_chapter_id'), 'quiz', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_quiz_lesson_id'), 'quiz', ['lesson_id'], unique=False)
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmark_user_id'), 'bookmark', ['user_id'], unique=False)
    op.create_table('practiceattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('chosen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practiceattempt_question_id'), 'practiceattempt', ['question_id'], unique=False)
    op.create_index(op.f('ix_practiceattempt_topic'), 'practiceattempt', ['topic'], unique=False)
    op.create_index(op.f('ix_practiceattempt_user_id'), 'practiceattempt', ['user_id'], unique=False)
    op.create_table('quizattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('answers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('time_taken_s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizattempt_quiz_id'), 'quizattempt', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quizattempt_user_id'), 'quizattempt', ['user_id'], unique=False)
    op.create_table('quizquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizquestion_question_id'), 'quizquestion', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizquestion_quiz_id'), 'quizquestion', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizquestion_quiz_id'), table_name='quizquestion')
    op.drop_index(op.f('ix_quizquestion_question_id'), table_name='quizquestion')
    op.drop_table('quizquestion')
    op.drop_index(op.f('ix_quizattempt_user_id'), table_name='quizattempt')
    op.drop_index(op.f('ix_quizattempt_quiz_id'), table_name='quizattempt')
    op.drop_table('quizattempt')
    op.drop_index(op.f('ix_practiceattempt_user_id'), table_name='practiceattempt')
    op.drop_index(op.f('ix_practiceattempt_topic'), table_name='practiceattempt')
    op.drop_index(op.f('ix_practiceattempt_question_id'), table_name='practiceattempt')
    op.drop_table('practiceattempt')
    op.drop_index(op.f('ix_bookmark_user_id'), table_name='bookmark')
    op.drop_table('bookmark')
    op.drop_index(op.f('ix_quiz_lesson_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_chapter_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_question_topic'), table_name='question')
    op.drop_index(op.f('ix_question_lesson_id'), table_name='question')
    op.drop_index(op.f('ix_question_chapter_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_lesson_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_note_user_id'), table_name='note')
    op.drop_index(op.f('ix_note_lesson_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_lesson_chapter_id'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_materialreport_material_id'), table_name='materialreport')
    op.drop_table('materialreport')
    op.drop_index(op.f('ix_enrollment_user_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_course_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_doubtreply_doubt_id'), table_name='doubtreply')
    op.drop_table('doubtreply')
    op.drop_index(op.f('ix_chapter_course_id'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_certificate_user_id'), table_name='certificate')
    op.drop_table('certificate')
    op.drop_index(op.f('ix_userbadge_user_id'), table_name='userbadge')
    op.drop_index(op.f('ix_userbadge_badge_code'), table_name='userbadge')
    op.drop_table('userbadge')
    op.drop_index(op.f('ix_topicstats_user_id'), table_name='topicstats')
    op.drop_index(op.f('ix_topicstats_topic'), table_name='topicstats')
    op.drop_index(op.f('ix_topicstats_subject_name'), table_name='topicstats')
    op.drop_table('topicstats')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_material_uploader_id'), table_name='material')
    op.drop_index(op.f('ix_material_subject_name'), table_name='material')
    op.drop_index(op.f('ix_material_class_grade'), table_name='material')
    op.drop_index(op.f('ix_material_board'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_doubt_student_id'), table_name='doubt')
    op.drop_table('doubt')
    op.drop_index(op.f('ix_dailyactivity_user_id'), table_name='dailyactivity')
    op.drop_index(op.f('ix_dailyactivity_date'), table_name='dailyactivity')
    op.drop_table('dailyactivity')
    op.drop_index(op.f('ix_course_subject_id'), table_name='course')
    op.drop_index(op.f('ix_course_slug'), table_name='course')
    op.drop_index(op.f('ix_course_class_grade'), table_name='course')
    op.drop_index(op.f('ix_course_board'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_textbook_subject_name'), table_name='textbook')
    op.drop_index(op.f('ix_textbook_lang'), table_name='textbook')
    op.drop_index(op.f('ix_textbook_class_grade'), table_name='textbook')
    op.drop_index(op.f('ix_textbook_board'), table_name='textbook')
    op.drop_table('textbook')
    op.drop_index(op.f('ix_subject_class_grade'), table_name='subject')
    op.drop_index(op.f('ix_subject_board'), table_name='subject')
    op.drop_table('subject')
    op.drop_table('school')
    op.drop_index(op.f('ix_passwordresetcode_email'), table_name='passwordresetcode')
    op.drop_table('passwordresetcode')
    op.drop_index(op.f('ix_board_name'), table_name='board')
    op.drop_table('board')
    op.drop_table('badgedef')
    # ### end Alembic commands ###
